### ISSUE TITLE
possible performace issue with unnicessary copies

### ISSUE THREAD

**Issue by odinthenerd** [halbux/sparselizard#13]
[here](https://github.com/halbux/sparselizard/blob/master/src/densematrix.cpp#L32) making valvec a reference would save a copy of a potentially large vector.

**Comment by halbux** [comment]
Hi,

I understand your point and believe it or not though about it but my final decision was that I want the user to be able to provide a vector defined inside the argument ({1,2,3}) for convenience... which therefore requires a copy because it would crash if passed as reference.

In general I optimize what actually slows down the code and this is probably 3 orders of magnitude faster than the actual calculation.

Regards,

Alexandre

**Comment by odinthenerd** [comment]
the problem with initialzer lists can be mitigated in other ways but I agree if its not a bottleneck no need to put effort into it

**Comment by bangerth** [comment]
I'm pretty sure that you can bind a temporary object created from an initializer list to a const reference.
