### ISSUE TITLE
Thermal radiation

### ISSUE THREAD

**Issue by hbadi** [halbux/sparselizard#14]
Hello Alex,

I want to try Sparcelizard for simulating coupled conduction-radiation 2D problems.
Does Sparselizard handle nonlinear Stefan-Boltzmann thermal radiation model (gray model body) ?

Best regards.

**Comment by halbux** [comment]
You mean the heat radiation proportional to epsilon*sigma*T^4? It definitely does.

Simply write your thermal conduction equation (see e.g. "CONDUCTOR HEATING DUE TO DC CURRENT" online example) and add your radiation term so something like this (check the signs etc.):

field T("h1);
...
formulation heatequation;
heatequation += integral(volume, grad(tf(T))*k*grad(dof(T)));
// Add the radiation heat going out:
heatequation += integral(volumeskin, -epsilon*sigma*pow(T,4) );

And solve with a nonlinear loop as done in the conductor heating example.

Alex
