### ISSUE TITLE
Question - setting to increase the number of cores/threads used.

### ISSUE THREAD

**Issue by caseyjamesdavis** [halbux/sparselizard#36]
Alex, thanks for creating, testing and documenting this awesome FEM library.

I am currently using it via the static library method.  

All the examples I have tried work great, but they only use 9 threads even if I make the mesh very large.

Is there a place to manually set the number of cores/threads?

Here are my machine details:

![image](https://user-images.githubusercontent.com/49321778/106666144-36ce4980-6575-11eb-8c81-9bdc673e1fbc.png)
![image](https://user-images.githubusercontent.com/49321778/106666175-3fbf1b00-6575-11eb-809a-a9c3ea3d7d6c.png)

Thanks for your help.

Cheers,
Casey

**Comment by halbux** [comment]
Hi Casey,

It should definitely be able to use more if it feels it s gonna improve the speed. I got all cores 100% used on a 16 cores core I9 and threadripper 32 cores.
The code is written in a way that I do not need to manage threads myself, they are created and managed during dgemm BLAS calls and parallel sort (on Linux) so openBLAS seems to be the culprit. Could it be because the static library is compiled on my 4cores laptop, for which I guess much more than 8 threads does not make sense?

In any case you can compile sparselizard yourself to solve the problem or try to set the max number of threads with something like:

setenv OMP_NUM_THREADS 4,3,2
(see https://www.openmp.org/spec-html/5.0/openmpse50.html ).

Alex

**Comment by caseyjamesdavis** [comment]
Hi Alex,

Thanks for the explanation.  Compiling on my machine seems like the best solution.

I have tried compiling a few times, and I think it works, but then I can't seem to get a simulation to execute.  I'm sure the issue is somewhere between the chair and keyboard ;-)

This what I have tried:
  git clone https://github.com/halbux/sparselizard.git
  cd sparselizard
  cd install_external_libs
  ./install_petsc.sh
  ./optional_install_gmsh_api.sh
  cd ..
  mkdir build
  cd build
  cmake ..
  cmake --build . -j$(nproc)

From this point on I'm less confident about what to do.
  cd ..
  make -j10
 copy main.cpp  and mesh file from 'examples' folder to 'sparselizard' folder ( I used nonlinear-electro-thermal-heating-3d)
 ./run_sparselizard.sh

This is the error I get.

![image](https://user-images.githubusercontent.com/49321778/106933744-42418200-66e7-11eb-91b7-839c1d206aa2.png)

Any ideas?

Thanks again for your help.

Casey

**Comment by halbux** [comment]
Looks good untill the less confident moment :)

After all the correct confident steps you can go to build/simulation/default and run ./default
This is the executable that was created during the build call, it is taken from sparselizard/simulation/default... so copy the example you want to run to simulations/default then build in the build folder and run the executable created in build/simulation/default. It will find all mesh files since they are copied as well automatically into build/simulation/default as you will see

**Comment by caseyjamesdavis** [comment]
Success, sparselizard is now using all my cores/threads!

htop:
![image](https://user-images.githubusercontent.com/49321778/106968960-ed6a2f80-6717-11eb-836f-75f54e44f6c8.png)

paraview:
![image](https://user-images.githubusercontent.com/49321778/106969849-aaa95700-6719-11eb-99a0-c0cb773dd1fd.png)


I recompiled again and was able to run ./default located in /sparselizard/build/simulations/default without the error. 

When I moved a different example main.cpp & disk.msh into /sparselizard/simulations/default and then:
- cmake ..
- cmake --build . -j$(nproc)

from the build directory it was like it had a memory and when I would run ./default it would always run the original simulation, not the new example.

I then followed the 'add project' instructions on your readme.md and everything works as expected.  The pictures above are the result of me adding an order of magnitude to the 2D base in the nonlinear-electro-thermal-heating-3d example.

The part I was missing was:
- source goes into  /sparselizard/simulations/X
- build (aka cmake .. and cmake --build . -j$(nproc) ) from the /sparselizard/build/
- run executable from /sparselizard/build/simulations/X

Now I can really play around.

Thanks so much for your help.

ps - I just noticed the scatter plot pdf and I think I understand the name of your program a bit better now :-)

**Comment by halbux** [comment]
That's excellent news! Congrats, you're the first user I know of to run on 128 threads.
For small simulations (but it is good to check once anyways) it might slow down to use 128 threads (I have sometimes gotten slightly faster results with num threads = num cores, so 64 in your case, this depends how fast your memory is as well, maybe worth checking the runtime with a sweep on number of threads). If you do that on a rather big problem please do not hesitate to share the sweep plot ).

Alex

**Comment by caseyjamesdavis** [comment]
A sweep of runtime vs number of threads on a large problem sounds like fun - I'm in.

Where and how do I limit the number of threads?

Casey

**Comment by caseyjamesdavis** [comment]
I think I figured it out.  I just added

`export OMP_NUM_THREADS=64`

to my .bashrc file.

**Comment by caseyjamesdavis** [comment]
It seems like the sweet spot on my machine is about 10 to 20 threads for 2D problems with millions of nodes.

![results](https://user-images.githubusercontent.com/49321778/107422502-1b20f100-6ae9-11eb-93b9-a4ffc5ff6d83.png)

**Comment by halbux** [comment]
Hi Casey,

It seems the number of cores is too strong compared to the memory speed so I am not so surprised by the graph. It might scale better with an interpolation order 2. 
Lets see in a few weeks how the new DDM algorithms will perform on a single machine.
Thanks for the sweep!

Concerning the heat equation:

You will find both the strong and the weak form in the example online "Conductor heating due to DC current" (on sparselizard.org).
You can also use 'predefineddiffusion' (see documentation) to have them written for you.

Alex
