### ISSUE TITLE
1D Beam elements in 3D space

### ISSUE THREAD

**Issue by j8asic** [halbux/sparselizard#46]
Can one have 1D elements in 3D space to simulate vibrations of beams? I.e. Timoshenko elements (or at least Euler-Bernoulli)?

**Comment by halbux** [comment]
Hi Josip,

You can do things in that direction with ports:

You set a lumped displacement/force (U/F) port on a region of the geometry
then you can use these in port relations, e.g. for a lumped spring F=kx you
can use something like this:

yourformulation += F - k*U;

This goes in the direction of what you want but not fully though.

Alex

**Comment by j8asic** [comment]
Thanks Alex for the info. So maybe I can reformulate the question: how could one implement vibration of a beam with varying I, J and E properties?

**Comment by halbux** [comment]
Well you can absolutely do that with classical FEM and sweeping the material properties!

Frequency analysis of a linear elasticity membrane vibration:
--> https://github.com/halbux/sparselizard/tree/master/examples/elasticity-membrane-3d

Eigenvalues of the same membrane for linear elasticity:
--> https://github.com/halbux/sparselizard/tree/master/examples/eigenvalues-elasticity-membrane-3d

Same but with a damped vibration:
--> https://github.com/halbux/sparselizard/tree/master/examples/eigenvalues-damped-elasticity-membrane-3d

Vibration of a prestressed object (or anything with geometric nonlinearity), linearized around a static deflection:
--> https://github.com/halbux/sparselizard/tree/master/examples/elasticity-geometric-nonlinearity-eigenvalues-3d

Vibration in the frequancy domain of elasticity with geometrix nonlinearity (taking new harmonics into account)
--> https://github.com/halbux/sparselizard-users/blob/main/examples/mechanic/vibration/backbone-curve-nonlinear-harmonic-balance/main.cpp


The beam geometry can be drawn with the gmsh api or, since it is simple with the native geometry drawer. Then put a sweep loop around it and you are done.

Alex

**Comment by j8asic** [comment]
Thanks for the infos!
