### ISSUE TITLE
boundary condition with time dependency

### ISSUE THREAD

**Issue by hbadi** [halbux/sparselizard#51]
Hi,

I'm trying to solve a classical parabolic equation : du/dt + laplacian(u) = 0, with a time dependency boundary condition du/dn=a*(u-u0(t))
When i update (+= operator) the formulation inside the time loop, do i need to "clear" the formulation due to the previous addings ?

Thanks.

PS : with a dirichelt bc (setconstraint), it works fine.

**Comment by halbux** [comment]
Hi Hamid,

May I kindly suggest to ask such question rather on the forum, which is meant for exactly that, in the future and keep the github issues for mostly bug reports and the like?

Answer:

Yes you would need to clean it, otherwise as the += syntax shows things would keep on accumulating. Although there are ways to avoid that this is not the way users are expected to work since there is a very clean way to make what you want work:

Situation 1: the only thing that changes in your boundary condition over time is the time value:

Then you can use expression "t()" as a part of your boundary condition expression and either let the time stepping algorithm increment the time value automatically (recommended) or use "settime(double timevalue)" yourself.
Note: if you have a time dependent profile defined by pieces you can conveniently create that with:

**Comment by hbadi** [comment]
Hi Alex,

Sorry, i'll do that on then forum next time for sure !

t() helped me a lot, i can define a time-dependent external temperature in this way :
`expression TempExt() { return 10.0*cos((mod(t(),86400) - 43200)*3.1415926 / 43200) + 283.15; }`
And use that in the formulation : 
`thermal += integral(tag1,  TempExt()*tf(v));`
Is that correct ?

**Comment by halbux** [comment]
If that's the expression you want I see no issues with it! Nice, it's the first time I see someone using the mod() function :)
Also: to define any function you want you can always use the custom function expression, which calls a function that you write yourself (see doc for keywords "custom function")

Alex
